# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev" do
  version "0.11.1"

  on_macos do
    on_intel do
      sha256 "4ed29953a6ce91fa75ef5feee87e24950ab230d86ff460d80ad9cd378180c8ec"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "76837d7d68c666df84d506aeeefe61748231309c4abe366086f0264c5aab1248"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "08efac51c42b4b05ebd2c0c55e48fe1df190d81dc36a0cb6b496c05fa2be3ede"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c532d1323022bfd6e0c3644ba82d468c0c059f5d06edfbd7281e55816a1f7b36"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev"
  desc "Run code in a container without learning Docker, in a sandbox closed by default"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dev"

  postflight do
    # The binary is not notarized, so macOS would quarantine it and
    # refuse to run it. Signing is on the roadmap; until then this is
    # the honest handling — and it is worth knowing that `brew` is
    # the reason a browser download would behave differently.
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    dev needs a container backend. On macOS that is OrbStack:
      brew install --cask orbstack

    Then check the setup, which changes nothing:
      dev doctor

    The first filtered run builds the egress sidecar image from source
    carried inside the binary, which takes a few minutes once.
  EOS
end
