# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "8264fbc9e78e60d1ddbfae0a236aabd570dced4f614b09e05d6ee74c3479326a"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "57b146966866f3454e113c5c2ce504cba8fb0575e506f70692ba4e3762737550"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b9857a82bcc6debf8cd73fc3aabe37dee58b601b55f39c6a2fb345197b0c637a"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8790241a35621fd30ee8c2fc7877d7d42b70e839ab27e4dc9e6b86402c8cce66"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev"
  desc "Run code in a container without learning Docker, in a sandbox closed by default"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dev"

  postflight do
    # The binary is not notarized, so macOS would quarantine it and
    # refuse to run it. Signing is on the roadmap; until then this is
    # the honest handling — and it is worth knowing that `brew` is
    # the reason a browser download would behave differently.
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    dev needs a container backend. On macOS that is OrbStack:
      brew install --cask orbstack

    Then check the setup, which changes nothing:
      dev doctor

    The first filtered run builds the egress sidecar image from source
    carried inside the binary, which takes a few minutes once.
  EOS
end
