# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.8.0" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "efbe2dc2cbc60537224733e7990612206be39af235ef121371e775d64bab8d75"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8d87f8ade94f006f9d8cbb89b668e943e8436cdd30854074363e300ec08d8b9"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7680da37e2730646c7ee01c8753b88fd06ffedbe1a6fad348249169f2fe64118"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7eab1698c1ba43e9ba3a9e6fda4ced95c603cb1dd2e9439f3d304f56ee9a9ace"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.8.0"
  desc "Run code in a container without learning Docker (pinned to 0.8.0)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
