# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.10.2" do
  version "0.10.2"

  on_macos do
    on_intel do
      sha256 "808020e2aab47cd8be81b89503f629ed81cde15040ae7eb73d0ff1a533eb09cf"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9aeffbb00b376fd38cc612609987281e65b42523bc1356fbf9cf47759a11dfce"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b940050909d9c09cfe286e5ffab260b8690897465c0fffcaf3a6e7af5dba5961"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "727424fde14fe2e4a6acf608c429564601c007e5f55e33f11e65a51a84ed182c"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.10.2"
  desc "Run code in a container without learning Docker (pinned to 0.10.2)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
