# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.7.0" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "087e617719968b9bef6715c0ff774d11f907a8c14fd3f9f5257adb0ccb383268"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "147df4f442059476f7881fd98c495d5279863c8d5eda75b5c23343f958aa8165"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b5ed452a88b33ccfcb3a19ca5220d9aee05e9baae99377f7f4cdcb2501eb8d56"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "161f8f43f3b65822c5752f65d175eeb05e7a418be39d75b460697816f68db380"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.7.0"
  desc "Run code in a container without learning Docker (pinned to 0.7.0)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
