# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.10.1" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "6f27a25754bc2189022783364fcba2fdd1a70ce576fe94c529da9d92008de6cd"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e8e5a97859fe5f719cc0de4219e8d3c88cb1046b7f685a6d615516da542de3a"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1de909bf3787805365ec2fe31381f9f1e55bf12fe11a98973e829cb79480b878"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb64ed4d8c59051ea2254606328b57206e4857ff3263c4405b04b7bb642cd938"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.10.1"
  desc "Run code in a container without learning Docker (pinned to 0.10.1)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
