# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.9.0" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "fba46ff4b10e2f87c6ca5ffdd56cf5861fd77ce85bc7a8a2682274fbed011da1"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a36715d7b891840134d17115a0bb41d7c1be29783a04309d29f7617f16ee986f"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5af329410b5469983831c00080649d489acc5f73d662a49651af350a073e3818"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6179703cf9800e7075be65de1f478794ad5352d5207efc8343dd13f20ead17c6"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.9.0"
  desc "Run code in a container without learning Docker (pinned to 0.9.0)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
