# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.10.0" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "3ec6d7cc338917e3ed93f6e62af38b3b74b7003deb977f4cced1d6323f218e9a"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "646070eee8463282652af631d7213d38e40792bb6ba44b66bd94f4ff2bbe3b49"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb872a132b822052b8dfa847401a81e51cbd83b5fd7c3503ac17c61a36dabcdc"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e4dbc0739d40e7ffd6454ce6a67e04dacd9a6273e6493aa631524644582aecdc"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.10.0"
  desc "Run code in a container without learning Docker (pinned to 0.10.0)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
