# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.6.0" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "ba0c6d4410d727d76924802fc50fe555debeac5cce1413d0a5fc4303a2384869"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f6205bc157b29378d6bbf17634019f3c8c486f486ca1d763e6716b7f0b34f54"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7cb745bb772d5e8116b0a35ef0cdc1b4fa8b23095bd9865c4470daaf1d521c9d"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c27a9a7e9028bd578493a57239fc3d4c817a264f2e941fcda958132a4e51f0ae"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.6.0"
  desc "Run code in a container without learning Docker (pinned to 0.6.0)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
