# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.11.2" do
  version "0.11.2"

  on_macos do
    on_intel do
      sha256 "eb23a95eeff51c2cb3b93a3578e2f682cda5a7751e06132282fff78da40db155"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "69bafcf4c8d374d1ab68b18d2ad3436ec966fae466f98783e7bc6f720b2219e6"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c55f653c5c4661a347d568ddcdb23cb821aceb4bbd7ed85a47af44670334974"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e85088bcfa9dbd0cc93629e5d4be0ad58856ca97ae82d6848346ed1f4fe0e6d"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.11.2"
  desc "Run code in a container without learning Docker (pinned to 0.11.2)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
