# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.8.1" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "f92f87bc68e0d4ed44722aa8d5972abeef0af8a2401182db99fcb6670b412867"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0058cd20aaea4d3fb33adf8527080181bb677c424fbd8b9e78b55e240a865439"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e09c07e4f8da15ec26790468aa64e9d71e0b4fddc86237c6f1173c197e16a6f7"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31b1dbed7197d12fc8095fe12e06457d5d915fb6cd4940a7ee92ceb7b1b2043c"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.8.1"
  desc "Run code in a container without learning Docker (pinned to 0.8.1)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
