# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.5.0" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "766f173c63d71128cecfecb24f453413a507c2855ed9ca87b902d105cca8fe62"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5797759e6a7265bd6578776432edfc407e8f8c7f40301f7b817f9eecd38c6741"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d685f7c6d17e15cb191fb742489fd8bf5cbdfa71e11e1bb9fc5aa102e41acb8d"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fcdfb12a033f063f4dbf6ef7ca80455d25cd302213803f75d3984dd10d06dd2"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.5.0"
  desc "Run code in a container without learning Docker (pinned to 0.5.0)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
