# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.11.0" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "8df10e312404f7d0589e849c9d88669f7c65e476e217b0d6361d2ded7ec1296a"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "43f1d86359afe00770e1a74eb6bb1c54eaeeda376cdfe45c83c37d305f617d34"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ab5d02ba58dd7fb7a9b6aebe0e170479d91ddeb3ca23f7afe158e4e80a16c9a"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b01368099faf8c75ecedcccf8047cb39a9eb20cd8a807db765ca0002ae6f192"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.11.0"
  desc "Run code in a container without learning Docker (pinned to 0.11.0)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
