# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.11.1" do
  version "0.11.1"

  on_macos do
    on_intel do
      sha256 "4ed29953a6ce91fa75ef5feee87e24950ab230d86ff460d80ad9cd378180c8ec"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "76837d7d68c666df84d506aeeefe61748231309c4abe366086f0264c5aab1248"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "08efac51c42b4b05ebd2c0c55e48fe1df190d81dc36a0cb6b496c05fa2be3ede"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c532d1323022bfd6e0c3644ba82d468c0c059f5d06edfbd7281e55816a1f7b36"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.11.1"
  desc "Run code in a container without learning Docker (pinned to 0.11.1)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
