# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev@0.12.0" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "a3c610b760477da458038159f6d35e3b0823dc757325077274f1f3da0dec7272"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e0df3de615ff307b85418ae017cbbc182744e5755d7d4ef67f8e508e3f4d8f2"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38689fb4935ef1c1c44a2c0f837674dc74c551565b39ff71e12b894aa97e28d1"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a616e4f78861bc5af683ba5c793011709e189184aa46cd81efb100ba1047f3d6"
      url "https://github.com/mwing/isolated-dev/releases/download/v#{version}/dev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev@0.12.0"
  desc "Run code in a container without learning Docker (pinned to 0.12.0)"
  homepage "https://github.com/mwing/isolated-dev"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dev",
    ]

  binary "dev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This is dev pinned to a specific version. `brew install --cask
    mwing/tap/dev` follows the latest release instead.
  EOS
end
